# Read-only comparison with the archived pre-rebuild production products.
suppressPackageStartupMessages({library(dplyr);library(readr);library(sf)})
root<-'output/residential_cluster_rebuild_20261007';before<-file.path(root,'before')
old<-read_csv(file.path(before,'output/part1/baseline_cluster_assignments.csv'),show_col_types=FALSE)
new<-read_csv('output/part1/baseline_cluster_assignments.csv',show_col_types=FALSE)
j<-inner_join(old,new,by='hex_id',suffix=c('_old','_new'))
transition<-count(j,tentative_name_old,tentative_name_new,name='hexes')
write_csv(transition,file.path(root,'part1_profile_transitions.csv'))
write_csv(count(new,tentative_name,concern_level,name='hexes'),file.path(root,'part1_profile_sizes.csv'))
write_csv(anti_join(new,select(old,hex_id),by='hex_id'),file.path(root,'part1_newly_eligible.csv'))
write_csv(anti_join(old,select(new,hex_id),by='hex_id'),file.path(root,'part1_no_longer_eligible.csv'))
write_csv(filter(j,tentative_name_old!=tentative_name_new),file.path(root,'part1_changed_profiles.csv'))
m<-st_drop_geometry(readRDS('output/part1/measurement/current_measurement.rds'))
ledger<-readRDS('output/part2/evictions/eviction_case_ledger.rds')
recent<-ledger %>% filter(file_date>=as.Date('2025-04-02'),file_date<=as.Date('2026-04-01'))
assigned<-recent %>% filter(assignment_status=='assigned_unique_hex') %>% mutate(hex_id=as.integer(assigned_hex_key)) %>% left_join(select(m,hex_id,residential_units,in_current_city_scope),by='hex_id')
stopifnot(!anyNA(assigned$residential_units))
write_csv(assigned %>% filter(residential_units<20) %>% count(hex_id,residential_units,in_current_city_scope,name='filings'),file.path(root,'remaining_low_unit_cells.csv'))
g<-readRDS('output/hex_grid.rds')
oldm<-st_drop_geometry(readRDS(file.path(before,'output/part1/measurement/current_measurement.rds')))
oldledger<-readRDS(file.path(before,'output/part2/evictions/eviction_case_ledger.rds'))
comparison<-recent %>% left_join(select(oldledger,case_number,old_status=assignment_status,old_hex=assigned_hex_key),by='case_number')
write_csv(filter(comparison,assignment_status!=old_status|coalesce(assigned_hex_key,'NA')!=coalesce(old_hex,'NA')),file.path(root,'changed_recent_cases.csv'))
p1<-list(previous_eligible=nrow(old),eligible=nrow(new),common_eligible=nrow(j),newly_eligible=nrow(anti_join(new,select(old,hex_id),by='hex_id')),no_longer_eligible=nrow(anti_join(old,select(new,hex_id),by='hex_id')),changed_profile=sum(j$tentative_name_old!=j$tentative_name_new),changed_concern=sum(j$concern_level_old!=j$concern_level_new),new_grid_eligible=sum(new$hex_id>7027),same_profile_share=mean(j$tentative_name_old==j$tentative_name_new))
a<-readRDS(file.path(before,'output/part2/clusters/part2_cluster_assignments.rds')) %>% filter(common_comparison_ready)
b<-readRDS('output/part2/clusters/part2_cluster_assignments.rds') %>% filter(common_comparison_ready)
map<-read_csv(file.path(root,'part2_proposed_mapping.csv'),show_col_types=FALSE)
y<-inner_join(a,b,by='hex_id',suffix=c('_old','_new'))
y$baseline_changed<-map$new[match(y$cluster_2025_old,map$old)]!=y$cluster_2025_new
y$fixed_changed<-map$new[match(y$cluster_2026_fixed_old,map$old)]!=y$cluster_2026_fixed_new
write_csv(filter(y,baseline_changed|fixed_changed),file.path(root,'part2_changed_profiles.csv'))
p2<-list(previous_common_sample=nrow(a),common_sample=nrow(b),shared_cells=nrow(y),newly_eligible=nrow(anti_join(b,select(a,hex_id),by='hex_id')),no_longer_eligible=nrow(anti_join(a,select(b,hex_id),by='hex_id')),changed_baseline_profiles=sum(y$baseline_changed),changed_current_fixed_profiles=sum(y$fixed_changed),previous_temporal_switches=sum(a$moved_fixed),temporal_switches=sum(b$moved_fixed))
result<-list(grid=jsonlite::read_json('output/hex_grid_manifest.json'),part1=p1,part2=p2,previous_units=sum(oldm$residential_units),units=sum(m$residential_units),new_grid_units=sum(m$residential_units[m$hex_id>7027]),recent_assigned_filings=nrow(assigned),low_unit_filings=sum(assigned$residential_units<20),low_unit_cells=n_distinct(assigned$hex_id[assigned$residential_units<20]),zero_unit_filings=sum(assigned$residential_units==0),zero_unit_cells=n_distinct(assigned$hex_id[assigned$residential_units==0]),new_grid_filings=sum(assigned$hex_id>7027))
jsonlite::write_json(result,file.path(root,'rebuild_comparison.json'),pretty=TRUE,auto_unbox=TRUE,digits=NA);print(result)
